= Minecraft Mods Station

This repository is an attempt to create documentation and manage resources for a Minecraft Mods station at http://hackthefuture.org[Hack the Future] events.

== Prerequisites

The following are recommended prerequisites for the Minecraft Mods station. Participants are not required to have them pre-installed; mentors can help install them at the event.  However, if they are pre-installed, participants can get started even faster.

. http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html[Java JDK 7]
. A Java IDE
.. Typically this has been http://www.minecraftforge.net/wiki/Eclipse[eclipse].
.. I like IntelliJ, but for consistency let's stick with eclipse for now.

We will be using Minecraft version 1.6.4 because Forge support for Minecraft 1.7.x is not ready yet.

== Links

HtF mentor Arun Gupta has written a README called https://github.com/devoxx4kids/materials/tree/master/workshops/minecraft[Minecraft Modding using Forge] for his devoxx4kids workshop.

== AsciiDoc Format

This README is in the http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax].  There is built-in support from GitHub, the https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia?hl=en[Asciidoctor.js Live Preview] for Chrome, a https://github.com/asciidoctor/asciidoctor-firefox-addon[Firefox Extension] and other tools available.
