= Minecraft Mods Station

This repository is an attempt to create documentation and
manage resources for a Minecraft Mods station at
http://hackthefuture.org[Hack the Future] events.

== System Requirements

Ideally a laptop to use with the Forge modding environment
should have at least

* a Core i7 CPU
* 8 GB of RAM

Compiling Java for such a large project can be CPU-intensive,
so a slower computer may result in much waiting throughout
each debug cycle. Furthermore, Forge has heavy memory
requirements, and a smaller physical RAM set may result
in less memory allocated to the JVM and obscure errors.

These problems are not insurmountable, but if you find
yourself with an underpowered machine at the Minecraft Mods
station, consider requesting a loaner laptop from the station
captain.

== Prerequisites

The following are recommended prerequisites for the Minecraft
Mods station. Mentors can help install them at the event.
However, if they are pre-installed, participants can get
started even faster.

* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java JDK 8]
* https://www.jetbrains.com/idea/#chooseYourEdition[IntelliJ IDEA Community Edition]

== Getting Started

Most of the lesson materials are currently stored on a Google
Drive folder. You can find an unpacked ForgeGradle project,
as well as a README with screenshots of various hack ideas.

* https://drive.google.com/drive/u/0/folders/0B3nL9cUsSr8-UmFYa19FVjFHQTA[Minecraft mods Gdrive folder]

Over time we hope to move these lessons to this page in
AsciiDoc format, avoiding the confusion of two READMEs.

== Links

Arun Gupta has written a README called
https://github.com/devoxx4kids/materials/blob/master/workshops/minecraft/readme-forge.asciidoc[Minecraft Modding using Forge]
for his devoxx4kids workshop.

Bob Freitas has written an
http://www.lopakalogic.com/articles/minecraft-articles/minecraft-mods-forge/[advanced tutorial for creating tools and weapons out of a new material, Red Diamond].

These tutorials have been used at past HtF events and may reference
Eclipse (another IDE) or older versions of Forge. With the help
of your mentors, however, these lessons can be readily adapted
to our modern environment.

== AsciiDoc Format

This README is in the
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax].
